[package]
name = "ex_3_1"
version = "0.1.2"
authors = ["Perfspec <lewisrwebb@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matches = "0.1.8"